// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAkEDgCWS8vxh4_hzDjzplPxpsptqpaKoA',
    appId: '1:454016135198:android:60837d0a983b685042be0f',
    messagingSenderId: '454016135198',
    projectId: 'bluemungan',
    databaseURL: 'https://bluemungan-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'bluemungan.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAbiJadYYr-wncb2yZ6cvWaUa1e25DwzmI',
    appId: '1:454016135198:ios:8772fe1af92e38af42be0f',
    messagingSenderId: '454016135198',
    projectId: 'bluemungan',
    databaseURL: 'https://bluemungan-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'bluemungan.appspot.com',
    androidClientId: '454016135198-4oh3rojlqe2913tlkd9vhmut99n709pd.apps.googleusercontent.com',
    iosClientId: '454016135198-d88sj8vf32m3lpeocuvc2h7djv06peu3.apps.googleusercontent.com',
    iosBundleId: 'com.shinjoo.bluemungan',
  );

}